export const MEGANAV = {
    LOAD: "MEGANAV_LOAD",
    RESPONSE: "MEGANAV_RESPONSE",
    ERROR: "MEGANAV_ERROR"
}

export const SEARCH = {
    LOAD: "SEARCH_LOAD",
    RESPONSE: "SEARCH_RESPONSE",
    ERROR: "SEARCH_ERROR"
}

export const PLP = {
    LOAD: "PLP_LOAD",
    RESPONSE: "PLP_RESPONSE",
    ERROR: "PLP_ERROR"
}